server:
  port: 8282
spring:
  application: community
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8
    username: root
    password: woshizhu123
  redis:
    open: true
    database: 2
    host: 127.0.0.1
    port: 6379
jwt:
  secret: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4K67DMlSPXbgG0MPp0gH
  expire: 86400000
  subject: door
# 配置 MyBatis XML 保存⽬录
mybatis-plus:
  mapper-locations: classpath:mybatis/*Mapper.xml

